name: Sensordemo
on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'
  create:
    paths-ignore:
    - '**.md'

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
    - name: Check out source code
      uses: actions/checkout@v1

    - name: Run SensorDemo Build and Test in Docker
      run: ./run_docker.sh

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: sensordemo-test-artifacts
        path: docker_script_output/
