/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgentApp model module.
 * @module model/AgentApp
 * @version 1.0.3
 */
class AgentApp {
    /**
     * Constructs a new <code>AgentApp</code>.
     * 
     * @alias module:model/AgentApp
     */
    constructor() { 
        
        AgentApp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgentApp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgentApp} obj Optional instance to populate.
     * @return {module:model/AgentApp} The populated <code>AgentApp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgentApp();

            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('running')) {
                obj['running'] = ApiClient.convertToType(data['running'], 'Boolean');
            }
            if (data.hasOwnProperty('diskUsage')) {
                obj['diskUsage'] = ApiClient.convertToType(data['diskUsage'], 'Number');
            }
            if (data.hasOwnProperty('Date')) {
                obj['Date'] = ApiClient.convertToType(data['Date'], 'Number');
            }
            if (data.hasOwnProperty('applicationType')) {
                obj['applicationType'] = ApiClient.convertToType(data['applicationType'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('bundleID')) {
                obj['bundleID'] = ApiClient.convertToType(data['bundleID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * 
 * @member {Array.<String>} tags
 */
AgentApp.prototype['tags'] = undefined;

/**
 * 
 * @member {Boolean} running
 */
AgentApp.prototype['running'] = undefined;

/**
 * 
 * @member {Number} diskUsage
 */
AgentApp.prototype['diskUsage'] = undefined;

/**
 * 
 * @member {Number} Date
 */
AgentApp.prototype['Date'] = undefined;

/**
 * 
 * @member {String} applicationType
 */
AgentApp.prototype['applicationType'] = undefined;

/**
 * 
 * @member {String} name
 */
AgentApp.prototype['name'] = undefined;

/**
 * 
 * @member {String} bundleID
 */
AgentApp.prototype['bundleID'] = undefined;






export default AgentApp;

