/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrialExtension from './TrialExtension';

/**
 * The DomainOptions model module.
 * @module model/DomainOptions
 * @version 1.0.3
 */
class DomainOptions {
    /**
     * Constructs a new <code>DomainOptions</code>.
     * 
     * @alias module:model/DomainOptions
     */
    constructor() { 
        
        DomainOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainOptions} obj Optional instance to populate.
     * @return {module:model/DomainOptions} The populated <code>DomainOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainOptions();

            if (data.hasOwnProperty('totpRequired')) {
                obj['totpRequired'] = ApiClient.convertToType(data['totpRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('trialExtension')) {
                obj['trialExtension'] = TrialExtension.constructFromObject(data['trialExtension']);
            }
        }
        return obj;
    }


}

/**
 * if true, totp is required
 * @member {Boolean} totpRequired
 */
DomainOptions.prototype['totpRequired'] = undefined;

/**
 * @member {module:model/TrialExtension} trialExtension
 */
DomainOptions.prototype['trialExtension'] = undefined;






export default DomainOptions;

