/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileChanges model module.
 * @module model/FileChanges
 * @version 1.0.3
 */
class FileChanges {
    /**
     * Constructs a new <code>FileChanges</code>.
     * 
     * @alias module:model/FileChanges
     */
    constructor() { 
        
        FileChanges.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FileChanges</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileChanges} obj Optional instance to populate.
     * @return {module:model/FileChanges} The populated <code>FileChanges</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileChanges();

            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'Number');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'Number');
            }
            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Optional New path
 * @member {String} path
 */
FileChanges.prototype['path'] = undefined;

/**
 * Optional New Mode
 * @member {Number} mode
 */
FileChanges.prototype['mode'] = undefined;

/**
 * Optional New Owner UID
 * @member {Number} uid
 */
FileChanges.prototype['uid'] = undefined;

/**
 * Optional New Group GID
 * @member {Number} gid
 */
FileChanges.prototype['gid'] = undefined;






export default FileChanges;

