/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GpioStateDefinition from './GpioStateDefinition';

/**
 * The GpiosState model module.
 * @module model/GpiosState
 * @version 1.0.3
 */
class GpiosState {
    /**
     * Constructs a new <code>GpiosState</code>.
     * Current state of GPIOs
     * @alias module:model/GpiosState
     */
    constructor() { 
        
        GpiosState.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GpiosState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GpiosState} obj Optional instance to populate.
     * @return {module:model/GpiosState} The populated <code>GpiosState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GpiosState();

            if (data.hasOwnProperty('led')) {
                obj['led'] = GpioStateDefinition.constructFromObject(data['led']);
            }
            if (data.hasOwnProperty('button')) {
                obj['button'] = GpioStateDefinition.constructFromObject(data['button']);
            }
            if (data.hasOwnProperty('switch')) {
                obj['switch'] = GpioStateDefinition.constructFromObject(data['switch']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GpioStateDefinition} led
 */
GpiosState.prototype['led'] = undefined;

/**
 * @member {module:model/GpioStateDefinition} button
 */
GpiosState.prototype['button'] = undefined;

/**
 * @member {module:model/GpioStateDefinition} switch
 */
GpiosState.prototype['switch'] = undefined;






export default GpiosState;

