/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VpnDefinition from './VpnDefinition';

/**
 * The InstanceServices model module.
 * @module model/InstanceServices
 * @version 1.0.0
 */
class InstanceServices {
    /**
     * Constructs a new <code>InstanceServices</code>.
     * @alias module:model/InstanceServices
     */
    constructor() { 
        
        InstanceServices.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstanceServices</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceServices} obj Optional instance to populate.
     * @return {module:model/InstanceServices} The populated <code>InstanceServices</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceServices();

            if (data.hasOwnProperty('vpn')) {
                obj['vpn'] = VpnDefinition.constructFromObject(data['vpn']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/VpnDefinition} vpn
 */
InstanceServices.prototype['vpn'] = undefined;






export default InstanceServices;

