/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Model model module.
 * @module model/Model
 * @version 1.0.3
 */
class Model {
    /**
     * Constructs a new <code>Model</code>.
     * 
     * @alias module:model/Model
     * @param type {String} 
     * @param name {String} 
     * @param flavor {String} 
     * @param model {String} 
     */
    constructor(type, name, flavor, model) { 
        
        Model.initialize(this, type, name, flavor, model);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, name, flavor, model) { 
        obj['type'] = type;
        obj['name'] = name;
        obj['flavor'] = flavor;
        obj['model'] = model;
    }

    /**
     * Constructs a <code>Model</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Model} obj Optional instance to populate.
     * @return {module:model/Model} The populated <code>Model</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Model();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('flavor')) {
                obj['flavor'] = ApiClient.convertToType(data['flavor'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('boardConfig')) {
                obj['boardConfig'] = ApiClient.convertToType(data['boardConfig'], 'String');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
            }
            if (data.hasOwnProperty('cpid')) {
                obj['cpid'] = ApiClient.convertToType(data['cpid'], 'Number');
            }
            if (data.hasOwnProperty('bdid')) {
                obj['bdid'] = ApiClient.convertToType(data['bdid'], 'Number');
            }
            if (data.hasOwnProperty('peripherals')) {
                obj['peripherals'] = ApiClient.convertToType(data['peripherals'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * 
 * @member {String} type
 */
Model.prototype['type'] = undefined;

/**
 * 
 * @member {String} name
 */
Model.prototype['name'] = undefined;

/**
 * 
 * @member {String} flavor
 */
Model.prototype['flavor'] = undefined;

/**
 * 
 * @member {String} description
 */
Model.prototype['description'] = undefined;

/**
 * 
 * @member {String} model
 */
Model.prototype['model'] = undefined;

/**
 * 
 * @member {String} boardConfig
 */
Model.prototype['boardConfig'] = undefined;

/**
 * 
 * @member {String} platform
 */
Model.prototype['platform'] = undefined;

/**
 * 
 * @member {Number} cpid
 */
Model.prototype['cpid'] = undefined;

/**
 * 
 * @member {Number} bdid
 */
Model.prototype['bdid'] = undefined;

/**
 * 
 * @member {Boolean} peripherals
 */
Model.prototype['peripherals'] = undefined;






export default Model;

