/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PasswordChangeBody model module.
 * @module model/PasswordChangeBody
 * @version 1.0.2
 */
class PasswordChangeBody {
    /**
     * Constructs a new <code>PasswordChangeBody</code>.
     * 
     * @alias module:model/PasswordChangeBody
     * @param user {String} userId
     * @param oldPassword {String} old password
     * @param newPassword {String} new password
     */
    constructor(user, oldPassword, newPassword) { 
        
        PasswordChangeBody.initialize(this, user, oldPassword, newPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user, oldPassword, newPassword) { 
        obj['user'] = user;
        obj['old-password'] = oldPassword;
        obj['new-password'] = newPassword;
    }

    /**
     * Constructs a <code>PasswordChangeBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PasswordChangeBody} obj Optional instance to populate.
     * @return {module:model/PasswordChangeBody} The populated <code>PasswordChangeBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordChangeBody();

            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('old-password')) {
                obj['old-password'] = ApiClient.convertToType(data['old-password'], 'String');
            }
            if (data.hasOwnProperty('new-password')) {
                obj['new-password'] = ApiClient.convertToType(data['new-password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * userId
 * @member {String} user
 */
PasswordChangeBody.prototype['user'] = undefined;

/**
 * old password
 * @member {String} old-password
 */
PasswordChangeBody.prototype['old-password'] = undefined;

/**
 * new password
 * @member {String} new-password
 */
PasswordChangeBody.prototype['new-password'] = undefined;






export default PasswordChangeBody;

