/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PeripheralsData model module.
 * @module model/PeripheralsData
 * @version 1.0.3
 */
class PeripheralsData {
    /**
     * Constructs a new <code>PeripheralsData</code>.
     * 
     * @alias module:model/PeripheralsData
     */
    constructor() { 
        
        PeripheralsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PeripheralsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PeripheralsData} obj Optional instance to populate.
     * @return {module:model/PeripheralsData} The populated <code>PeripheralsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PeripheralsData();

            if (data.hasOwnProperty('acceleration')) {
                obj['acceleration'] = ApiClient.convertToType(data['acceleration'], ['Number']);
            }
            if (data.hasOwnProperty('gyroscope')) {
                obj['gyroscope'] = ApiClient.convertToType(data['gyroscope'], ['Number']);
            }
            if (data.hasOwnProperty('magnetic')) {
                obj['magnetic'] = ApiClient.convertToType(data['magnetic'], ['Number']);
            }
            if (data.hasOwnProperty('orientation')) {
                obj['orientation'] = ApiClient.convertToType(data['orientation'], ['Number']);
            }
            if (data.hasOwnProperty('temperature')) {
                obj['temperature'] = ApiClient.convertToType(data['temperature'], 'Number');
            }
            if (data.hasOwnProperty('proximity')) {
                obj['proximity'] = ApiClient.convertToType(data['proximity'], 'Number');
            }
            if (data.hasOwnProperty('light')) {
                obj['light'] = ApiClient.convertToType(data['light'], 'Number');
            }
            if (data.hasOwnProperty('pressure')) {
                obj['pressure'] = ApiClient.convertToType(data['pressure'], 'Number');
            }
            if (data.hasOwnProperty('humidity')) {
                obj['humidity'] = ApiClient.convertToType(data['humidity'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * 
 * @member {Array.<Number>} acceleration
 */
PeripheralsData.prototype['acceleration'] = undefined;

/**
 * 
 * @member {Array.<Number>} gyroscope
 */
PeripheralsData.prototype['gyroscope'] = undefined;

/**
 * 
 * @member {Array.<Number>} magnetic
 */
PeripheralsData.prototype['magnetic'] = undefined;

/**
 * 
 * @member {Array.<Number>} orientation
 */
PeripheralsData.prototype['orientation'] = undefined;

/**
 * 
 * @member {Number} temperature
 */
PeripheralsData.prototype['temperature'] = undefined;

/**
 * 
 * @member {Number} proximity
 */
PeripheralsData.prototype['proximity'] = undefined;

/**
 * 
 * @member {Number} light
 */
PeripheralsData.prototype['light'] = undefined;

/**
 * 
 * @member {Number} pressure
 */
PeripheralsData.prototype['pressure'] = undefined;

/**
 * 
 * @member {Number} humidity
 */
PeripheralsData.prototype['humidity'] = undefined;






export default PeripheralsData;

