/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 3.9.0-13085
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SnapshotCreationOptions model module.
 * @module model/SnapshotCreationOptions
 * @version 1.0.1
 */
class SnapshotCreationOptions {
    /**
     * Constructs a new <code>SnapshotCreationOptions</code>.
     * @alias module:model/SnapshotCreationOptions
     * @param name {String} Snapshot name
     */
    constructor(name) { 
        
        SnapshotCreationOptions.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>SnapshotCreationOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SnapshotCreationOptions} obj Optional instance to populate.
     * @return {module:model/SnapshotCreationOptions} The populated <code>SnapshotCreationOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SnapshotCreationOptions();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Snapshot name
 * @member {String} name
 */
SnapshotCreationOptions.prototype['name'] = undefined;






export default SnapshotCreationOptions;

