/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TouchCurveInput model module.
 * @module model/TouchCurveInput
 * @version 1.0.2
 */
class TouchCurveInput {
    /**
     * Constructs a new <code>TouchCurveInput</code>.
     * 
     * @alias module:model/TouchCurveInput
     */
    constructor() { 
        
        TouchCurveInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TouchCurveInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TouchCurveInput} obj Optional instance to populate.
     * @return {module:model/TouchCurveInput} The populated <code>TouchCurveInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TouchCurveInput();

            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], Object);
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], Object);
            }
        }
        return obj;
    }


}

/**
 * Finger Positions
 * @member {Object} start
 */
TouchCurveInput.prototype['start'] = undefined;

/**
 * Finger Positions
 * @member {Object} end
 */
TouchCurveInput.prototype['end'] = undefined;






export default TouchCurveInput;

