/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import TrialRequestMetadata from './TrialRequestMetadata';

/**
 * The TrialRequestOptions model module.
 * @module model/TrialRequestOptions
 * @version 1.0.3
 */
class TrialRequestOptions {
    /**
     * Constructs a new <code>TrialRequestOptions</code>.
     * 
     * @alias module:model/TrialRequestOptions
     */
    constructor() { 
        
        TrialRequestOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrialRequestOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrialRequestOptions} obj Optional instance to populate.
     * @return {module:model/TrialRequestOptions} The populated <code>TrialRequestOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrialRequestOptions();

            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = TrialRequestMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('enterprise')) {
                obj['enterprise'] = ApiClient.convertToType(data['enterprise'], 'Boolean');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Address} address
 */
TrialRequestOptions.prototype['address'] = undefined;

/**
 * The user's email address.
 * @member {String} email
 */
TrialRequestOptions.prototype['email'] = undefined;

/**
 * The user's full name.
 * @member {String} name
 */
TrialRequestOptions.prototype['name'] = undefined;

/**
 * @member {module:model/TrialRequestMetadata} metadata
 */
TrialRequestOptions.prototype['metadata'] = undefined;

/**
 * If true, create an enterprise domain.
 * @member {Boolean} enterprise
 */
TrialRequestOptions.prototype['enterprise'] = undefined;

/**
 * Stripe payment token.
 * @member {String} token
 */
TrialRequestOptions.prototype['token'] = undefined;






export default TrialRequestOptions;

