/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 3.9.0-13085
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserError model module.
 * @module model/UserError
 * @version 1.0.1
 */
class UserError {
    /**
     * Constructs a new <code>UserError</code>.
     * @alias module:model/UserError
     * @param error {String} Error text
     * @param errorID {module:model/UserError.ErrorIDEnum} Error ID
     */
    constructor(error, errorID) { 
        
        UserError.initialize(this, error, errorID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error, errorID) { 
        obj['error'] = error;
        obj['errorID'] = errorID;
    }

    /**
     * Constructs a <code>UserError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserError} obj Optional instance to populate.
     * @return {module:model/UserError} The populated <code>UserError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserError();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('errorID')) {
                obj['errorID'] = ApiClient.convertToType(data['errorID'], 'String');
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Error text
 * @member {String} error
 */
UserError.prototype['error'] = undefined;

/**
 * Error ID
 * @member {module:model/UserError.ErrorIDEnum} errorID
 */
UserError.prototype['errorID'] = undefined;

/**
 * Field associated with error
 * @member {String} field
 */
UserError.prototype['field'] = undefined;





/**
 * Allowed values for the <code>errorID</code> property.
 * @enum {String}
 * @readonly
 */
UserError['ErrorIDEnum'] = {

    /**
     * value: "UserError"
     * @const
     */
    "UserError": "UserError"
};



export default UserError;

