/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1LoadExtensionParameters model module.
 * @module model/V1LoadExtensionParameters
 * @version 1.0.3
 */
class V1LoadExtensionParameters {
    /**
     * Constructs a new <code>V1LoadExtensionParameters</code>.
     * 
     * @alias module:model/V1LoadExtensionParameters
     * @param imageId {String} The uuid of the image to load
     */
    constructor(imageId) { 
        
        V1LoadExtensionParameters.initialize(this, imageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, imageId) { 
        obj['imageId'] = imageId;
    }

    /**
     * Constructs a <code>V1LoadExtensionParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1LoadExtensionParameters} obj Optional instance to populate.
     * @return {module:model/V1LoadExtensionParameters} The populated <code>V1LoadExtensionParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1LoadExtensionParameters();

            if (data.hasOwnProperty('imageId')) {
                obj['imageId'] = ApiClient.convertToType(data['imageId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The uuid of the image to load
 * @member {String} imageId
 */
V1LoadExtensionParameters.prototype['imageId'] = undefined;






export default V1LoadExtensionParameters;

