/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstanceState from './InstanceState';

/**
 * The V1SetStateBody model module.
 * @module model/V1SetStateBody
 * @version 1.0.0
 */
class V1SetStateBody {
    /**
     * Constructs a new <code>V1SetStateBody</code>.
     * @alias module:model/V1SetStateBody
     * @param state {module:model/InstanceState} 
     */
    constructor(state) { 
        
        V1SetStateBody.initialize(this, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state) { 
        obj['state'] = state;
    }

    /**
     * Constructs a <code>V1SetStateBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1SetStateBody} obj Optional instance to populate.
     * @return {module:model/V1SetStateBody} The populated <code>V1SetStateBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1SetStateBody();

            if (data.hasOwnProperty('state')) {
                obj['state'] = InstanceState.constructFromObject(data['state']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InstanceState} state
 */
V1SetStateBody.prototype['state'] = undefined;






export default V1SetStateBody;

