/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 3.9.0-13085
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VpnDefinition model module.
 * @module model/VpnDefinition
 * @version 1.0.1
 */
class VpnDefinition {
    /**
     * Constructs a new <code>VpnDefinition</code>.
     * @alias module:model/VpnDefinition
     */
    constructor() { 
        
        VpnDefinition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VpnDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VpnDefinition} obj Optional instance to populate.
     * @return {module:model/VpnDefinition} The populated <code>VpnDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VpnDefinition();

            if (data.hasOwnProperty('proxy')) {
                obj['proxy'] = ApiClient.convertToType(data['proxy'], ['String']);
            }
            if (data.hasOwnProperty('listeners')) {
                obj['listeners'] = ApiClient.convertToType(data['listeners'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} proxy
 */
VpnDefinition.prototype['proxy'] = undefined;

/**
 * @member {Array.<String>} listeners
 */
VpnDefinition.prototype['listeners'] = undefined;






export default VpnDefinition;

