# coding: utf-8

"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import avh_api_async
from avh_api_async.models.instance_input import InstanceInput  # noqa: E501
from avh_api_async.rest import ApiException

class TestInstanceInput(unittest.TestCase):
    """InstanceInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceInput(self):
        """Test InstanceInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
