/**
 * Arm API
 *    This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)   
 *
 * The version of the OpenAPI document: 3.15.0-15704
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvhApi);
  }
}(this, function(expect, AvhApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvhApi.InstanceBootOptions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InstanceBootOptions', function() {
    it('should create an instance of InstanceBootOptions', function() {
      // uncomment below and update the code to test InstanceBootOptions
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be.a(AvhApi.InstanceBootOptions);
    });

    it('should have the property bootArgs (base name: "bootArgs")', function() {
      // uncomment below and update the code to test the property bootArgs
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property restoreBootArgs (base name: "restoreBootArgs")', function() {
      // uncomment below and update the code to test the property restoreBootArgs
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property udid (base name: "udid")', function() {
      // uncomment below and update the code to test the property udid
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property ecid (base name: "ecid")', function() {
      // uncomment below and update the code to test the property ecid
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property randomSeed (base name: "randomSeed")', function() {
      // uncomment below and update the code to test the property randomSeed
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property pac (base name: "pac")', function() {
      // uncomment below and update the code to test the property pac
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property aprr (base name: "aprr")', function() {
      // uncomment below and update the code to test the property aprr
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

    it('should have the property additionalTags (base name: "additionalTags")', function() {
      // uncomment below and update the code to test the property additionalTags
      //var instance = new AvhApi.InstanceBootOptions();
      //expect(instance).to.be();
    });

  });

}));
