/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 3.9.0-13085
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvhApi);
  }
}(this, function(expect, AvhApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvhApi.Model();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Model', function() {
    it('should create an instance of Model', function() {
      // uncomment below and update the code to test Model
      //var instance = new AvhApi.Model();
      //expect(instance).to.be.a(AvhApi.Model);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property flavor (base name: "flavor")', function() {
      // uncomment below and update the code to test the property flavor
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property boardConfig (base name: "boardConfig")', function() {
      // uncomment below and update the code to test the property boardConfig
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property platform (base name: "platform")', function() {
      // uncomment below and update the code to test the property platform
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property cpid (base name: "cpid")', function() {
      // uncomment below and update the code to test the property cpid
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property bdid (base name: "bdid")', function() {
      // uncomment below and update the code to test the property bdid
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

    it('should have the property peripherals (base name: "peripherals")', function() {
      // uncomment below and update the code to test the property peripherals
      //var instance = new AvhApi.Model();
      //expect(instance).to.be();
    });

  });

}));
