/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 3.9.0-13085
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvhApi);
  }
}(this, function(expect, AvhApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvhApi.PeripheralsData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PeripheralsData', function() {
    it('should create an instance of PeripheralsData', function() {
      // uncomment below and update the code to test PeripheralsData
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be.a(AvhApi.PeripheralsData);
    });

    it('should have the property acceleration (base name: "acceleration")', function() {
      // uncomment below and update the code to test the property acceleration
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property gyroscope (base name: "gyroscope")', function() {
      // uncomment below and update the code to test the property gyroscope
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property magnetic (base name: "magnetic")', function() {
      // uncomment below and update the code to test the property magnetic
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property orientation (base name: "orientation")', function() {
      // uncomment below and update the code to test the property orientation
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property temperature (base name: "temperature")', function() {
      // uncomment below and update the code to test the property temperature
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property proximity (base name: "proximity")', function() {
      // uncomment below and update the code to test the property proximity
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property light (base name: "light")', function() {
      // uncomment below and update the code to test the property light
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property pressure (base name: "pressure")', function() {
      // uncomment below and update the code to test the property pressure
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

    it('should have the property humidity (base name: "humidity")', function() {
      // uncomment below and update the code to test the property humidity
      //var instance = new AvhApi.PeripheralsData();
      //expect(instance).to.be();
    });

  });

}));
