/**
 * Arm API
 * REST API to manage your virtual devices.
 *
 * The version of the OpenAPI document: 3.9.0-13085
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvhApi);
  }
}(this, function(expect, AvhApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvhApi.ProjectQuota();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectQuota', function() {
    it('should create an instance of ProjectQuota', function() {
      // uncomment below and update the code to test ProjectQuota
      //var instance = new AvhApi.ProjectQuota();
      //expect(instance).to.be.a(AvhApi.ProjectQuota);
    });

    it('should have the property cores (base name: "cores")', function() {
      // uncomment below and update the code to test the property cores
      //var instance = new AvhApi.ProjectQuota();
      //expect(instance).to.be();
    });

    it('should have the property instances (base name: "instances")', function() {
      // uncomment below and update the code to test the property instances
      //var instance = new AvhApi.ProjectQuota();
      //expect(instance).to.be();
    });

    it('should have the property ram (base name: "ram")', function() {
      // uncomment below and update the code to test the property ram
      //var instance = new AvhApi.ProjectQuota();
      //expect(instance).to.be();
    });

  });

}));
