"""
    Arm API

       This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)     # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.created_by import CreatedBy
from avh_api.model.instance_agent_state import InstanceAgentState
from avh_api.model.instance_boot_options import InstanceBootOptions
from avh_api.model.instance_netmon_state import InstanceNetmonState
from avh_api.model.instance_services import InstanceServices
from avh_api.model.instance_state import InstanceState
globals()['CreatedBy'] = CreatedBy
globals()['InstanceAgentState'] = InstanceAgentState
globals()['InstanceBootOptions'] = InstanceBootOptions
globals()['InstanceNetmonState'] = InstanceNetmonState
globals()['InstanceServices'] = InstanceServices
globals()['InstanceState'] = InstanceState
from avh_api.model.instance import Instance


class TestInstance(unittest.TestCase):
    """Instance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstance(self):
        """Test Instance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Instance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
