"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.grant_trial_request_response import GrantTrialRequestResponse


class TestGrantTrialRequestResponse(unittest.TestCase):
    """GrantTrialRequestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantTrialRequestResponse(self):
        """Test GrantTrialRequestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GrantTrialRequestResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
