"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.address import Address
from avh_api.model.trial_request_metadata import TrialRequestMetadata
globals()['Address'] = Address
globals()['TrialRequestMetadata'] = TrialRequestMetadata
from avh_api.model.trial_request_options import TrialRequestOptions


class TestTrialRequestOptions(unittest.TestCase):
    """TrialRequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrialRequestOptions(self):
        """Test TrialRequestOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrialRequestOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
