"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.9.0-13085
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.instance_boot_options import InstanceBootOptions


class TestInstanceBootOptions(unittest.TestCase):
    """InstanceBootOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceBootOptions(self):
        """Test InstanceBootOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceBootOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
