"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.instance_netmon_state import InstanceNetmonState


class TestInstanceNetmonState(unittest.TestCase):
    """InstanceNetmonState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceNetmonState(self):
        """Test InstanceNetmonState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceNetmonState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
