"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.instance_state import InstanceState
globals()['InstanceState'] = InstanceState
from avh_api.model.v1_set_state_body import V1SetStateBody


class TestV1SetStateBody(unittest.TestCase):
    """V1SetStateBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1SetStateBody(self):
        """Test V1SetStateBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1SetStateBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
