"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.web_player_session import WebPlayerSession


class TestWebPlayerSession(unittest.TestCase):
    """WebPlayerSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebPlayerSession(self):
        """Test WebPlayerSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WebPlayerSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
