"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.snapshot_status import SnapshotStatus
globals()['SnapshotStatus'] = SnapshotStatus
from avh_api.model.snapshot import Snapshot


class TestSnapshot(unittest.TestCase):
    """Snapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshot(self):
        """Test Snapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Snapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
