"""
    Arm API

       This documents the Arm Virtual Hosting REST API.  For other examples and API clients such as python or javascript please see [API Clients (python/javascript)](https://github.com/ARM-software/avh-api).   For a guide on using this interface please see [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   ## Links   - [API Quickstart](https://intercom.help/arm-avh/en/articles/6134791-quickstart-for-the-api-docs)   - [API Clients (python/javascript)](https://github.com/arm-software/avh-api)     # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.coupon_options import CouponOptions
from avh_api.model.plan import Plan
from avh_api.model.trial import Trial
globals()['CouponOptions'] = CouponOptions
globals()['Plan'] = Plan
globals()['Trial'] = Trial
from avh_api.model.subscriber_invite import SubscriberInvite


class TestSubscriberInvite(unittest.TestCase):
    """SubscriberInvite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriberInvite(self):
        """Test SubscriberInvite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriberInvite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
