"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.agent_value_return import AgentValueReturn


class TestAgentValueReturn(unittest.TestCase):
    """AgentValueReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentValueReturn(self):
        """Test AgentValueReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgentValueReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
