"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.v1_create_hook_parameters import V1CreateHookParameters


class TestV1CreateHookParameters(unittest.TestCase):
    """V1CreateHookParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CreateHookParameters(self):
        """Test V1CreateHookParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1CreateHookParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
