"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.firmware import Firmware
globals()['Firmware'] = Firmware
from avh_api.model.model_software import ModelSoftware


class TestModelSoftware(unittest.TestCase):
    """ModelSoftware unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelSoftware(self):
        """Test ModelSoftware"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelSoftware()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
