"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.agent_app import AgentApp
globals()['AgentApp'] = AgentApp
from avh_api.model.agent_apps_list import AgentAppsList


class TestAgentAppsList(unittest.TestCase):
    """AgentAppsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentAppsList(self):
        """Test AgentAppsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgentAppsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
