"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.agent_system_adb_auth import AgentSystemAdbAuth


class TestAgentSystemAdbAuth(unittest.TestCase):
    """AgentSystemAdbAuth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentSystemAdbAuth(self):
        """Test AgentSystemAdbAuth"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgentSystemAdbAuth()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
