"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.instance_boot_options import InstanceBootOptions
globals()['InstanceBootOptions'] = InstanceBootOptions
from avh_api.model.patch_instance_options import PatchInstanceOptions


class TestPatchInstanceOptions(unittest.TestCase):
    """PatchInstanceOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchInstanceOptions(self):
        """Test PatchInstanceOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchInstanceOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
