"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.invite_revoke_params_ids import InviteRevokeParamsIds
globals()['InviteRevokeParamsIds'] = InviteRevokeParamsIds
from avh_api.model.invite_revoke_params import InviteRevokeParams


class TestInviteRevokeParams(unittest.TestCase):
    """InviteRevokeParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInviteRevokeParams(self):
        """Test InviteRevokeParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InviteRevokeParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
