"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.vpn_definition import VpnDefinition


class TestVpnDefinition(unittest.TestCase):
    """VpnDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnDefinition(self):
        """Test VpnDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
