"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.rotate_body import RotateBody


class TestRotateBody(unittest.TestCase):
    """RotateBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRotateBody(self):
        """Test RotateBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RotateBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
