"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.kernel_thread import KernelThread
globals()['KernelThread'] = KernelThread
from avh_api.model.kernel_task import KernelTask


class TestKernelTask(unittest.TestCase):
    """KernelTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKernelTask(self):
        """Test KernelTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KernelTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
