"""
    Arm API

    REST API to manage your virtual devices.  # noqa: E501

    The version of the OpenAPI document: 3.15.0-15704
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import avh_api
from avh_api.model.v1_load_extension_parameters import V1LoadExtensionParameters


class TestV1LoadExtensionParameters(unittest.TestCase):
    """V1LoadExtensionParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1LoadExtensionParameters(self):
        """Test V1LoadExtensionParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1LoadExtensionParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
